import { Toaster } from "@/components/ui/toaster";
import { Toaster as SonnerToaster } from '@/components/ui/sonner';
import "../globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}>
        <div className="min-h-screen bg-background">
          {children}
        </div>
        <Toaster />
        <SonnerToaster />
      </body>
    </html>
  )
}


